server:
  port: 8085

api:
  defillama:
    domain: 'api.llama.fi/v2/historicalChainTvl'
    endpoints: 
      ethereum: '/Ethereum'
      solana: '/Solana'

database: 
  db-name: "db_2403"

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/${database.db-name}"
    username: "postgres"
    password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update
  # Hibernate ddl auto (create, create-drop, validate, update)
